management:
  endpoints:
    web:
      base-path: /
      exposure:
        include:
        - "*"
server:
  port: 8080
  servlet:
    context-path: /api/catalog
spring:
  datasource:
    url: "jdbc:oracle:thin:@localhost:1521/FREEPDB1"
    username: DMUSER
    password: 12345
    ##driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    generate-ddl: false
    
